---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/orders/{id}":
    get:
      summary: Retrieves an order
      tags:
      - Orders
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  customer:
                    type: string
                  employee_id:
                    type: integer
                  order_date:
                    type: string
                    format: date
                  required_date:
                    type: string
                    format: date
                  shipped_date:
                    type: string
                    format: date
                  shipped_id:
                    type: integer
                  freight:
                    type: number
                    format: float
                required:
                - id
                - name
                - status
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  customer:
                    type: string
                  employee_id:
                    type: integer
                  order_date:
                    type: string
                    format: date
                  required_date:
                    type: string
                    format: date
                  shipped_date:
                    type: string
                    format: date
                  shipped_id:
                    type: integer
                  freight:
                    type: number
                    format: float
                required:
                - id
                - name
                - status
        '404':
          description: Order not found
    put:
      summary: update an order
      tags:
      - Orders
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Order updated
        '422':
          description: invalid request
        '401':
          description: Unauthorised User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer:
                  type: string
                employee_id:
                  type: integer
                order_date:
                  type: string
                  format: date
                required_date:
                  type: string
                  format: date
                shipped_date:
                  type: string
                  format: date
                shipped_id:
                  type: integer
                freight:
                  type: number
                  format: float
              required:
              - id
              - customer
              - employee_id
              - order_date
              - required_date
              - shipped_date
              - shipped_id
              - freight
    delete:
      summary: delete an order
      tags:
      - Orders
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '401':
          description: Unauthorised User
        '404':
          description: Order record not found
  "/orders":
    get:
      summary: Retrieves all orders
      tags:
      - Orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                    customer:
                      type: string
                    employee_id:
                      type: integer
                    order_date:
                      type: string
                      format: date
                    required_date:
                      type: string
                      format: date
                    shipped_date:
                      type: string
                      format: date
                    shipped_id:
                      type: integer
                    freight:
                      type: number
                      format: float
                required:
                - id
                - customer
                - employee_id
                - order_date
                - required_date
                - shipped_date
                - shipped_id
                - freight
        '422':
          description: invalid request
    post:
      summary: Creates an order
      tags:
      - Orders
      parameters: []
      responses:
        '201':
          description: order created
        '422':
          description: invalid request
        '401':
          description: Unauthorised User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                customer:
                  type: string
                employee_id:
                  type: integer
                order_date:
                  type: string
                  format: date
                required_date:
                  type: string
                  format: date
                shipped_date:
                  type: string
                  format: date
                shipped_id:
                  type: integer
                freight:
                  type: number
                  format: float
              required:
              - id
              - customer
              - employee_id
              - order_date
              - required_date
              - shipped_date
              - shipped_id
              - freight
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: orderapi99.fly.dev
