---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/companies/{id}":
    get:
      summary: Retrieves an organization
      tags:
      - Organizations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Organization found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  organization_id:
                    type: string
                  website:
                    type: string
                  founded:
                    type: string
                    format: date
                  number_of_employees:
                    type: integer
                  industry:
                    type: string
                  description:
                    type: string
                  country:
                    type: string
                required:
                - id
                - name
                - status
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  organization_id:
                    type: string
                  website:
                    type: string
                  founded:
                    type: string
                    format: date
                  number_of_employees:
                    type: integer
                  industry:
                    type: string
                  description:
                    type: string
                  country:
                    type: string
                required:
                - id
                - name
                - status
        '404':
          description: Organization not found
    put:
      summary: update an organization
      tags:
      - Organizations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Organization updated
        '422':
          description: invalid request
        '401':
          description: Unauthorised User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                website:
                  type: string
                founded:
                  type: string
                  format: date
                number_of_employees:
                  type: integer
                industry:
                  type: string
                description:
                  type: string
                country:
                  type: string
              required:
              - name
              - website
              - founded
              - number_of_employees
              - industry
              - description
              - country
    delete:
      summary: delete an organization
      tags:
      - Organizations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '401':
          description: Unauthorised User
        '404':
          description: Organization record not found
  "/companies":
    get:
      summary: Retrieves all organization
      tags:
      - Organizations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    organization_id:
                      type: string
                    website:
                      type: string
                    founded:
                      type: string
                      format: date
                    number_of_employees:
                      type: integer
                    industry:
                      type: string
                    description:
                      type: string
                    country:
                      type: string
                required:
                - id
                - organization_id
                - name
                - website
                - country
                - founded
                - industry
                - description
                - number_of_employees
        '422':
          description: invalid request
    post:
      summary: Creates an organization
      tags:
      - Organizations
      parameters: []
      responses:
        '201':
          description: organization created
        '422':
          description: invalid request
        '401':
          description: Unauthorised User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                organization_id:
                  type: string
                website:
                  type: string
                founded:
                  type: string
                  format: date
                number_of_employees:
                  type: integer
                industry:
                  type: string
                description:
                  type: string
                country:
                  type: string
              required:
              - organization_id
              - name
              - website
              - country
              - founded
              - industry
              - description
              - number_of_employees
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: organizationsapi.fly.dev
